
# http://wiki.ros.org/costmap_2d/hydro/obstacles
max_obstacle_height: 2.0  # assume something like an arm is mounted on top of the robot
min_obstacle_height: 0.0
inf_is_valid: true
obstacle_range: 2.5
raytrace_range: 3.0

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.6  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
#robot_radius: 0.4509 # ArloBot
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular
inflation_radius: 0.55  # max. distance from an obstacle at which costs are incurred for planning paths.
cost_scaling_factor: 10  # exponential rate at which the obstacle cost drops off (default: 10)

# http://wiki.ros.org/costmap_2d/hydro/obstacles#VoxelCostmapPlugin
# voxel map configuration; z-voxels 0 are filled by bumpers and 1 by laser scan (kinect)
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
publish_voxel_map: true

observation_sources: scan bump
# observation_sources: scan
# observation_sources: bump

# scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.25, max_obstacle_height: 0.35}
# Our lasers (Xtion and fake) either needs to publish a height, or set min_obstacle_height to 0.0:
# http://wiki.ros.org/navigation/Troubleshooting#Missing_Obstacles_in_Costmap2D
# Note taht the max_obstacle_height is very important too!
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3}
# Can we just set up two of these here?
bump: {data_type: PointCloud2, topic: camera/depth/points, marking: true, clearing: false, min_obstacle_height: 0.0, max_obstacle_height: 0.15}
