
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 20.0
controller_patience: 5.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

# local planner - default is trajectory rollout
# base_local_planner: "dwa_local_planner/DWAPlannerROS"
